services:
  postgresdb:
    image: postgres:18.0
    container_name: postgres_mrp
    restart: unless-stopped #startet container bei crash neu
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
      POSTGRES_DB: mrpdb
    ports:
      - 5432:5432
    volumes:
      - swen1v:/var/lib/postgresql

volumes:
  swen1v: